repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: ["--unsafe"]
      - id: check-json
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.0
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: ./.bin/run-mypy
        language: system
        types: [python]
        require_serial: true
        files: ^(src|packages|stubs)/.+\.(py|pyi)$
        pass_filenames: true
